### ISSUE TITLE
加入网址评级标准

### ISSUE THREAD

**Issue by luckzhiwei** [luckzhiwei/ss-speed-test-client#30]

**Comment by linanwx** [comment]
暂时从http://alexa.chinaz.com/Country/index_US.html网页下拉alexa排名，使用参数-a来指定输出文件。暂时全部设置为黑名单即需要代理访问，因为这个排名是美国的排名，大部分还是需要代理访问的。但是其中也有一些网址例如百度应该是白名单的 @luckzhiwei
