### ISSUE TITLE
补充界面上需要改进的地方

### ISSUE THREAD

**Issue by luckzhiwei** [luckzhiwei/ss-speed-test-client#50]
* todo 
* 支持edittext粘贴复制
 * 测速界面旋转有bug
 * 首页的加号按钮使用原生控件
 * 页面跳转点击加上波纹效果

**Comment by linanwx** [comment]
在某些机型上确认按钮有问题。
![image](https://user-images.githubusercontent.com/16589958/34461659-fc698888-ee6a-11e7-9237-2c97c80507c8.png)

**Comment by linanwx** [comment]
修改界面密码建议明文显示。或者在后面加一个眼睛按钮，按下去就可以明文显示。
这样设置的初衷是用户也可以把本软件当做一个保存ss服务器地址和密码的备忘程序。

**Comment by luckzhiwei** [comment]
收到

**Comment by luckzhiwei** [comment]
改进测滑界面

**Comment by luckzhiwei** [comment]
改进加密方式选择控件

**Comment by linanwx** [comment]
后台自动测速间隔可调 @luckzhiwei
