### ISSUE TITLE
关于后台自动测速太费流量的问题

### ISSUE THREAD

**Issue by linanwx** [luckzhiwei/ss-speed-test-client#52]
统计了一下，现在后台自动测速大约会花费5MB左右的流量。

- 减少测速花费的流量？少设置一些网址可以吗？
- 仅在WIFI下自动测速？在测速之前判断当前网络是否是WIFI环境，否则不测速？还是在设置页面加上开关？

**Comment by linanwx** [comment]
现在这个应用比较危险，没有划掉后台的情况下会一直跑流量。请注意

**Comment by luckzhiwei** [comment]
@linanwx ,可以考虑仅仅在wifi环境下测速，在设置页面添加
