### ISSUE TITLE
预研ss正向代理的demo ，目标是完成多ss服务器评分

### ISSUE THREAD

**Issue by luckzhiwei** [luckzhiwei/ss-speed-test-client#9]

**Comment by linanwx** [comment]
似乎需要将shadowsocks-libv中的local.c文件成功编译至Android平台

**Comment by luckzhiwei** [comment]
已经编译完成ss-local,准备尝试

**Comment by luckzhiwei** [comment]
ss-local 目前在android的api中，只在android 7.0以上的手机才支持，原因在于：httpurlconnection的proxy在6.0的及其6.0以下的手机，只支持sock4版本的协议，而ss-local是socks5版本的协议。因此，由于碎片化的问题，我们目前只支持7.0的手机

**Comment by luckzhiwei** [comment]
@linanwx ，考虑编译privoxy android版本，来支持http转socks5代理，从native解决这个问题

**Comment by luckzhiwei** [comment]
上述privoxy的问题已经解决，可以在7.0版本下面的手机运行privoxy，来将http request 转化为socks请求
